name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - runs: npm install
    - runs: npm test
